baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Moji-Moji Web Experience'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
